homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: [redacted]
  longitude: [redacted]
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: [redacted]
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yweather

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# David config
# Mosquitto
mqtt:
  broker: [redacted]
  port: [redacted]
  client_id: [redacted]
  username: [redacted]
  password: [redacted]

# https://www.home-assistant.io/components/sensor.mqtt/ 
# https://github.com/mertenats/open-home-automation/tree/master/ha_mqtt_sensor_dht22
sensor 1:
  platform: mqtt
  state_topic: 'house/salon'
  name: 'Temperature'
  unit_of_measurement: '°C'
  value_template: '{{ value_json.temperature }}'

sensor 2:
  platform: mqtt
  state_topic: 'house/salon'
  name: 'Humidity'
  unit_of_measurement: '%'
  value_template: '{{ value_json.humidity }}'

switch 1:
  - platform: mqtt
    name: "Caldera"
    state_topic: "/house/switchCaldera/"
    command_topic: "/house/switchCalderaCmd/"
    payload_on: "1"
    payload_off: "0"
    qos: 0
    retain: true    

    #input_number:
    #  target_temp:
    #    name: Target Heater Temperature Slider
    #min: 15
    #    max: 25
    #    step: 1
    #    unit_of_measurement: "C"
    #    icon: mdi:target

climate:
  - platform: generic_thermostat
    name: Caldera
    heater: switch.Caldera
    target_sensor: sensor.Temperature
    min_temp: 13
    max_temp: 19
    target_temp: 15
    tolerance: 0.3
    initial_operation_mode: "off"

    #weather:
    #- platform: darksky
    #api_key: [redacted]

light:
  - platform: xiaomi_miio
    name: Xiaomi Philips Smart LED Ball
    host: [redacted]
    token: [redacted]
    model: philips.light.bulb

group:
  Caldera:
    name: Caldera
    entities:
      - switch.Caldera
      - climate.Caldera
    icon: mdi:home
    #view: true

automation:
- alias: 'Caleccion OFF at 00:00H'
  trigger:
          platform: time
          at: '23:59:59'
  condition:
          condition: state
          entity_id: switch.caldera
          state: 'on'
  action:
          - service: switch.turn_off
            entity_id: switch.caldera


- alias: 'Calefaccion ON at 21:00' 
  trigger:
          platform: time
          at: '21:00:00'
  condition:
   - condition: and
     conditions:
     - condition: time
       weekday:
       - mon
       - tue
       - wed
       - thu
       - sun
     - condition: state
       entity_id: switch.caldera
       state: 'off'
  action:
     - service: switch.turn_on
       entity_id: switch.caldera

- alias: 'Calefaccion OFF si>19'
  trigger:
     platform: numeric_state
     entity_id: sensor.temperature
     above: 18.5
     for:
        minutes: 2
  condition:
    condition: state
    entity_id: switch.caldera
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.caldera
    #- service: notify.telegram
    #  data:
    #    message: "La Temperatura del Comedor Está Por Encima de 22, Calefaccion OFF"
